import sqg2oconst

UNRELIABLE = sqg2oconst.UNRELIABLE
UNRELIABLE_SEQUENCED = sqg2oconst.UNRELIABLE_SEQUENCED
RELIABLE = sqg2oconst.RELIABLE
RELIABLE_ORDERED = sqg2oconst.RELIABLE_ORDERED
RELIABLE_SEQUENCED = sqg2oconst.RELIABLE_SEQUENCED