site_name: PyG2O

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - sane_lists

plugins:
  - mkdocstrings
  - search
  - callouts
  
repo_url: https://github.com/AURUMVORXX/PyG2O.git
  
nav:
  - How to use: index.md
  - QnA: qna.md
  - Classes:
    - Network:
      - Packet: classes/network/Packet.md
  - Constants:
    - AntiCheat: constants/anticheat.md
    - Context: constants/context.md
    - Damage: constants/damage.md
    - General: constants/general.md
    - Hand: constants/hand.md
    - Item: constants/item.md
    - Network: constants/network.md
    - NPC: constants/npc.md
    - Reliability: constants/reliability.md
    - Skill weapon: constants/skill-weapon.md
    - Talent: constants/talent.md
    - Weapon mode: constants/weapon-mode.md
    - Weather: constants/weather.md
  - Events:
    - General:
      - onInit: defaultEvents/general/onInit.md
      - onExit: defaultEvents/general/onExit.md
      - onTick: defaultEvents/general/onTick.md
      - onTime: defaultEvents/general/onTime.md
      - onBan: defaultEvents/general/onBan.md
      - onUnban: defaultEvents/general/onUnban.md
    - Network:
      - onPacket: defaultEvents/network/onPacket.md
    - Player:
      - onPlayerChangeColor: defaultEvents/player/onPlayerChangeColor.md
      - onPlayerChangeFocus: defaultEvents/player/onPlayerChangeFocus.md
      - onPlayerChangeHealth: defaultEvents/player/onPlayerChangeHealth.md
      - onPlayerChangeMana: defaultEvents/player/onPlayerChangeMana.md
      - onPlayerChangeMaxHealth: defaultEvents/player/onPlayerChangeMaxHealth.md
      - onPlayerChangeMaxMana: defaultEvents/player/onPlayerChangeMaxMana.md
      - onPlayerChangeWeaponMode: defaultEvents/player/onPlayerChangeWeaponMode.md
      - onPlayerChangeWorld: defaultEvents/player/onPlayerChangeWorld.md
      - onPlayerCommand: defaultEvents/player/onPlayerCommand.md
      - onPlayerDead: defaultEvents/player/onPlayerDead.md
      - onPlayerDisconnect: defaultEvents/player/onPlayerDisconnect.md
      - onPlayerEnterWorld: defaultEvents/player/onPlayerEnterWorld.md
      - onPlayerEquipAmulet: defaultEvents/player/onPlayerEquipAmulet.md
      - onPlayerEquipArmor: defaultEvents/player/onPlayerEquipArmor.md
      - onPlayerEquipBelt: defaultEvents/player/onPlayerEquipBelt.md
      - onPlayerEquipHandItem: defaultEvents/player/onPlayerEquipHandItem.md
      - onPlayerEquipHelmet: defaultEvents/player/onPlayerEquipHelmet.md
      - onPlayerEquipMeleeWeapon: defaultEvents/player/onPlayerEquipMeleeWeapon.md
      - onPlayerEquipRangedWeapon: defaultEvents/player/onPlayerEquipRangedWeapon.md
      - onPlayerEquipRing: defaultEvents/player/onPlayerEquipRing.md
      - onPlayerEquipShield: defaultEvents/player/onPlayerEquipShield.md
      - onPlayerEquipSpell: defaultEvents/player/onPlayerEquipSpell.md
      - onPlayerJoin: defaultEvents/player/onPlayerJoin.md
      - onPlayerMessage: defaultEvents/player/onPlayerMessage.md
      - onPlayerMobInteract: defaultEvents/player/onPlayerMobInteract.md
      - onPlayerRespawn: defaultEvents/player/onPlayerRespawn.md
      - onPlayerShoot: defaultEvents/player/onPlayerShoot.md
      - onPlayerSpellCast: defaultEvents/player/onPlayerSpellCast.md
      - onPlayerSpellSetup: defaultEvents/player/onPlayerSpellSetup.md
      - onPlayerTeleport: defaultEvents/player/onPlayerTeleport.md
      - onPlayerToggleFaceAni: defaultEvents/player/onPlayerToggleFaceAni.md
  - Functions:
    - Events: 
      - event: events/event.md
      - removeEventHandler: events/removeEventHandler.md
      - addEvent: events/addEvent.md
      - callEvent: events/callEvent.md
  - How to build: howtobuild.md

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
        
      primary: black