site_name: PyG2O

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - sane_lists

plugins:
  - mkdocstrings
  - search
  - callouts
  
repo_url: https://github.com/AURUMVORXX/PyG2O.git
  
nav:
  - How to use: howtouse.md
  - QnA: qna.md
  - Events:
    - General:
      - onInit: defaultEvents/onInit.md
      - onExit: defaultEvents/onExit.md
      - onTick: defaultEvents/onTick.md
      - onTime: defaultEvents/onTime.md
      - onBan: defaultEvents/onBan.md
      - onUnban: defaultEvents/onUnban.md
  - Functions:
    - Events: 
      - event: events/event.md
      - removeEventHandler: events/removeEventHandler.md
      - addEvent: events/addEvent.md
      - callEvent: events/callEvent.md
  - How to build: howtobuild.md

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
        
      primary: black