import sqg2oconst

DAMAGE_UNKNOWN = sqg2oconst.DAMAGE_UNKNOWN
DAMAGE_BARRIER = sqg2oconst.DAMAGE_BARRIER
DAMAGE_BLUNT = sqg2oconst.DAMAGE_BLUNT
DAMAGE_EDGE = sqg2oconst.DAMAGE_EDGE
DAMAGE_FIRE = sqg2oconst.DAMAGE_FIRE
DAMAGE_FLY = sqg2oconst.DAMAGE_FLY
DAMAGE_MAGIC = sqg2oconst.DAMAGE_MAGIC
DAMAGE_POINT = sqg2oconst.DAMAGE_POINT
DAMAGE_FALL = sqg2oconst.DAMAGE_FALL