import sqg2oconst

TALENT_1H = sqg2oconst.TALENT_1H
TALENT_2H = sqg2oconst.TALENT_2H
TALENT_BOW = sqg2oconst.TALENT_BOW
TALENT_CROSSBOW = sqg2oconst.TALENT_CROSSBOW
TALENT_PICK_LOCKS = sqg2oconst.TALENT_PICK_LOCKS
TALENT_PICKPOCKET = sqg2oconst.TALENT_PICKPOCKET
TALENT_MAGE = sqg2oconst.TALENT_MAGE
TALENT_SNEAK = sqg2oconst.TALENT_SNEAK
TALENT_REGENERATE = sqg2oconst.TALENT_REGENERATE
TALENT_FIREMASTER = sqg2oconst.TALENT_FIREMASTER
TALENT_ACROBATIC = sqg2oconst.TALENT_ACROBATIC
TALENT_PICKPOCKET_UNUSED = sqg2oconst.TALENT_PICKPOCKET_UNUSED
TALENT_SMITH = sqg2oconst.TALENT_SMITH
TALENT_RUNES = sqg2oconst.TALENT_RUNES
TALENT_ALCHEMY = sqg2oconst.TALENT_ALCHEMY
TALENT_THROPHY = sqg2oconst.TALENT_THROPHY
TALENT_A = sqg2oconst.TALENT_A
TALENT_B = sqg2oconst.TALENT_B
TALENT_C = sqg2oconst.TALENT_C
TALENT_D = sqg2oconst.TALENT_D
TALENT_E = sqg2oconst.TALENT_E
TALENT_MAX = sqg2oconst.TALENT_MAX