import sqg2oconst

WEAPONMODE_NONE = sqg2oconst.WEAPONMODE_NONE
WEAPONMODE_FIST = sqg2oconst.WEAPONMODE_FIST
WEAPONMODE_DAG = sqg2oconst.WEAPONMODE_DAG
WEAPONMODE_1HS = sqg2oconst.WEAPONMODE_1HS
WEAPONMODE_2HS = sqg2oconst.WEAPONMODE_2HS
WEAPONMODE_BOW = sqg2oconst.WEAPONMODE_BOW
WEAPONMODE_CBOW = sqg2oconst.WEAPONMODE_CBOW
WEAPONMODE_MAG = sqg2oconst.WEAPONMODE_MAG
WEAPONMODE_MAX = sqg2oconst.WEAPONMODE_MAX