name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          pip install mkdocs
          pip install "mkdocstrings[python]"
          pip install mkdocs-material
          pip install mkdocs-callouts
          pip install mkdocs-glightbox
          cd docs/
          mkdocs gh-deploy --force